version:                "3"
services:
  sp:
      image:            sims-pars-dev:latest
      volumes:
        - ./notebooks:/home/jovyan/work
        - ./sims_pars:/home/jovyan/work/sims_pars
      ports:
        - 8888:8888
      container_name:   sims-pars-test