FROM sims-pars-dev:latest

LABEL maintainer="TimeWz667 <timewz667@gmail.com>"
LABEL name="sims-pars"

RUN pip install -i https://test.pypi.org/simple/sims-pars

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
